---
title: "Infection Intensity Data Analysis"
author: "Lindsay E. Martin"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load libraries needed:
library(readxl)
library(writexl)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(car) 
library(ggpubr)

library(lattice)
library(MASS)

require(pscl) 
library(lmtest)
library(sandwich)
require(foreign)
require(fitdistrplus)

#import the data:
II_Data <- read_xlsx("Infection_Intensity_Data_JS_May2022.xlsx",
                     sheet = "R")
                     #col_types = c()) #import all PO Data

#format factors:
II_Data$Temperature <- as.factor(II_Data$Temperature)
II_Data$Age <- as.factor(II_Data$Age)
II_Data$Block <- as.factor(II_Data$Block)

str(II_Data)

#create labels for axes
templabs <- c("27˚C","30˚C","32˚C")
names(templabs)<- c("27","30","32")

agelabs <- c("1 day","5 days", "10 days", "15 days")
names(agelabs)<-c("1","5","10","15")
```

## Exploring the Data

```{r echo=FALSE}
II_Data %>%
  count(Temperature,CFUs,Age)%>%
  ggplot(aes(x=Temperature,y=CFUs,color=Age))+ 
  scale_shape_identity(guide="legend")+
  geom_point()+
  facet_grid(Temperature~Age, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title=~italic("E. coli")~" Infection Intensity",
       x="Temperature (˚C)",parse=TRUE)+
  ylab(expression(~italic("E. coli")~" CFUs"))+theme_bw()+
  theme(legend.position = "none")

II_Data %>%
  count(Temperature,CFUs,Age)%>%
  ggplot(aes(x=Temperature,y=CFUs,color=Age))+ 
  scale_shape_identity(guide="legend")+
  geom_point()+
  facet_grid(~Age, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title=~italic("E. coli")~" Infection Intensity",
       x="Temperature (˚C)",parse=TRUE)+
  ylab(expression(~italic("E. coli")~" CFUs"))+theme_bw()+
  theme(legend.position = "none")

II_Data %>%
  count(Temperature,CFUs,Age)%>%
  ggplot(aes(x=Age,y=CFUs,color=Temperature))+ 
  scale_shape_identity(guide="legend")+
  geom_point()+
  facet_grid(~Temperature, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title=~italic("E. coli")~" Infection Intensity",
       x="Age (days post eclosion)",parse=TRUE)+
  ylab(expression(~italic("E. coli")~" CFUs"))+theme_bw()+
  theme(legend.position = "none")

#Graph 1b: raw data, age vs. CFUs
II_Data %>%
  count(Temperature,CFUs,Age)%>%
  ggplot(aes(x=Age,y=CFUs, color=Temperature))+ 
  scale_shape_identity(guide="legend")+
  geom_point()+
  facet_grid(Temperature~Age, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title=~italic("E. coli")~" Infection Intensity",
       x="Adult Age (days post eclosion)",parse=TRUE)+
  ylab(expression(~italic("E. coli")~" CFUs"))+theme_bw()+
  theme(legend.position = "none")

#Graph 2a: box plot of raw data, temp vs. CFUs
II_Data %>%
  ggplot(aes(x=Temperature,y=CFUs,color=Age))+
  facet_grid(Temperature~Age, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title=~italic("E. coli")~" Infection Intensity",
       x="Temperature (˚C)")+
  ylab(expression(~italic("E. coli")~" CFUs"))+
  #stat_summary(fun=mean,geom="point",shape=23,size=4)+
  geom_boxplot(notch = TRUE)+theme_bw()+
  geom_dotplot(binaxis='y', stackdir='center', dotsize=1.3)+
  theme(legend.position = "none")

II_Data %>%
  ggplot(aes(x=Temperature,y=CFUs,color=Age))+
  facet_grid(~Age, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title=~italic("E. coli")~" Infection Intensity",
       x="Temperature (˚C)")+
  ylab(expression(~italic("E. coli")~" CFUs"))+
  geom_boxplot(notch = TRUE)+theme_bw()+
  geom_dotplot(binaxis='y', stackdir='center', dotsize=0.5)+
  theme(legend.position = "none")

#Graph 2b: box plot of raw data, temp vs. CFUs
II_Data %>%
  ggplot(aes(x=Age,y=CFUs,color=Temperature))+
  facet_grid(Temperature~Age, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title=~italic("E. coli")~" Infection Intensity",
       x="Adult Age (days post eclosion)")+
  ylab(expression(~italic("E. coli")~" CFUs"))+
  #stat_summary(fun=mean,geom="point",shape=23,size=4)+
  geom_boxplot(notch = TRUE)+theme_bw()+
  geom_dotplot(binaxis='y', stackdir='center', dotsize=1.3)+
  theme(legend.position = "none")

II_Data %>%
  ggplot(aes(x=Age,y=CFUs,color=Temperature))+
  facet_grid(~Temperature, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title=~italic("E. coli")~" Infection Intensity",
       x="Adult Age (days post eclosion)")+
  ylab(expression(~italic("E. coli")~" CFUs"))+
  geom_boxplot(notch = TRUE)+theme_bw()+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=0.5)+
  theme(legend.position = "none")
```

## Data Summary Figures

First, we can calculate the mean, median, SE, etc.

```{r}
#calculate the mean, median, SE, sd, etc.:
II_Summary <- II_Data %>%
  group_by(Temperature,Age) %>%
  summarise(mean_CFUs = mean(CFUs),
            median_CFUs = median(CFUs),
            sd_CFUs = sd(CFUs),
            n_CFUs = n(),
            SE_CFUs = sd(CFUs)/sqrt(n()))
```

Then, we can graph the arithmetic means:

```{r}
#arithmetic means graphed:
II_Summary %>%
  count(Temperature,mean_CFUs,Age,SE_CFUs)%>%
  ggplot(aes(x=Temperature,y=mean_CFUs,color=Age,
             ymin=mean_CFUs-SE_CFUs, ymax=mean_CFUs+SE_CFUs))+
  geom_point()+
  facet_grid(Temperature~Age, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title="Mean "~italic("E. coli")~" Infection Intensity",
       x="Temperature (˚C)")+
  ylab(expression(~italic("E. coli")~" CFUs"))+
  geom_errorbar()+ theme_bw()+
  scale_shape(guide="none") + theme(legend.position = "none")

head(II_Summary)

II_Summary %>%
  count(Temperature,mean_CFUs,Age,SE_CFUs)%>%
  ggplot(aes(x=Temperature,y=mean_CFUs,color=Age,
             ymin=mean_CFUs-SE_CFUs, ymax=mean_CFUs+SE_CFUs))+
  geom_point()+
  facet_grid(~Age, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title="Mean "~italic("E. coli")~" Infection Intensity",
       x="Temperature (˚C)")+
  ylab(expression(~italic("E. coli")~" CFUs"))+
  geom_errorbar()+ theme_bw()+
  scale_shape(guide="none") + theme(legend.position = "none")

II_Summary %>%
  count(Temperature,mean_CFUs,Age,SE_CFUs)%>%
  ggplot(aes(x=Age,y=mean_CFUs,color=Temperature,
             ymin=mean_CFUs-SE_CFUs, ymax=mean_CFUs+SE_CFUs))+
  geom_point()+
  facet_grid(~Temperature, labeller = labeller(Age=agelabs, Temperature=templabs))+
  labs(title="Mean "~italic("E. coli")~" Infection Intensity",
       x="Adult Age (days post eclosion)")+
  ylab(expression(~italic("E. coli")~" CFUs"))+
  geom_errorbar()+ theme_bw()+
  scale_shape(guide="none") + theme(legend.position = "none")
```
